plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.maven.publish)
}

android {
    compileSdkVersion libs.versions.compileSdkVersion.get() as int

    defaultConfig {
        namespace "com.github.liaoheng.adapter"
        minSdk libs.versions.minSdk.get() as int
        targetSdk libs.versions.targetSdk.get() as int
    }
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    testImplementation libs.robolectric
    testImplementation libs.junit

    implementation libs.androidx.core
    implementation libs.androidx.recyclerview
    implementation(libs.androidx.swiperefreshlayout) {
        exclude module: 'core'
    }
    compileOnly(libs.androidx.appcompat){
        exclude module: 'activity'
        exclude module: 'collection'
    }
    compileOnly "com.hannesdorfmann:adapterdelegates4:4.3.2"
}

import com.vanniktech.maven.publish.AndroidSingleVariantLibrary
mavenPublishing {
    configure(new AndroidSingleVariantLibrary("release", true, false))
}