plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.maven.publish)
}

android {
    compileSdkVersion libs.versions.compileSdkVersion.get() as int

    defaultConfig {
        namespace "com.github.liaoheng.ui"
        minSdk libs.versions.minSdk.get() as int
        targetSdk libs.versions.targetSdk.get() as int
    }
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    testImplementation libs.robolectric
    testImplementation libs.junit

    implementation libs.androidx.appcompat

    compileOnly libs.rxlifecycle4
    compileOnly libs.rxlifecycle4.android

    implementation project(':common-core')
    implementation project(':common-adapter')
}

import com.vanniktech.maven.publish.AndroidSingleVariantLibrary
mavenPublishing {
    configure(new AndroidSingleVariantLibrary("release", true, false))
}