plugins {
    alias(libs.plugins.android.application)
}

android {
    compileSdkVersion libs.versions.compileSdkVersion.get() as int

    defaultConfig {
        namespace "com.github.liaoheng.common.sample"
        minSdk libs.versions.minSdk.get() as int
        targetSdk libs.versions.targetSdk.get() as int
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
    buildFeatures {
        viewBinding true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation libs.junit

    implementation libs.androidx.appcompat
    implementation libs.androidx.recyclerview
    implementation libs.androidx.coordinatorlayout
    implementation libs.androidx.browser

    implementation libs.glide
    annotationProcessor libs.glide.compiler
    implementation libs.glide.okhttp3.integration

    implementation libs.rxlifecycle4
    implementation libs.rxlifecycle4.android
    implementation libs.jackson.annotations
    implementation libs.jackson.databind
    implementation libs.jackson.core
    implementation libs.rxandroid3
    implementation libs.rxjava3

    implementation project(':common-core')
    implementation project(':common-ui')
    implementation project(':common-adapter')
    implementation project(':common-net')
}