plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.maven.publish)
}

android {
    compileSdkVersion libs.versions.compileSdkVersion.get() as int

    defaultConfig {
        namespace "com.github.liaoheng"
        minSdk libs.versions.minSdk.get() as int
        targetSdk libs.versions.targetSdk.get() as int
    }
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    testImplementation libs.robolectric
    testImplementation libs.junit
    testImplementation libs.joda.time

    implementation libs.androidx.annotation
    implementation libs.androidx.core
    implementation libs.google.guava
    implementation libs.joda.time.android

    compileOnly libs.jackson.annotations
    compileOnly libs.jackson.databind
    compileOnly libs.jackson.core
    compileOnly libs.rxandroid3
    compileOnly libs.rxjava3
}

import com.vanniktech.maven.publish.AndroidSingleVariantLibrary
mavenPublishing {
    configure(new AndroidSingleVariantLibrary("release", true, false))
}